version: '3.0'
services:
   cddb:
     container_name: cddb
     build:
       context: .
       dockerfile: ./Build_Containers/Dockerfile-mysql
     image: cd/cddb:1.0.0
     ports:
       - "3306:3306"
     # volumes:
     #       - /docker/cds/mysql:/var/lib/mysql
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: secret123
     command: --explicit_defaults_for_timestamp


   cdapi:
     container_name: cdapi
     build:
       context: .
       dockerfile: ./Build_Containers/Dockerfile-cdapi
     image: cd/cdapi:1.0.0
     links:
       - cddb:cddb
     ports:
       - "8080:8080"
     restart: always
     depends_on:
       - cddb
